trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g apifox-cli
    apifox run --access-token APS-gXi214Gb9s4cxxPtM0g5FQUa9XBZR1X4 -t 345149 -e 345183 -n 1 -r html,cli
  displayName: 'Install Apifox CLI and Run Tests'
